# -*- coding: utf-8 -*-
"""
The purpose of the tool are:
1) language translating
2) OSD indexing
"""
__software__ = "Multi-language converting tool"
__version__ = "1.00"
__author__ = "Jiang Yu-Kuan <york_jiang@mars-semi.com.tw>"
__date__ = "2012/11/27 (initial version) ~ 2012/11/29 (last revision)"

import os
import sys

import xlrd

#-----------------------------------------------------------------------------

def prefix_authorship(lines, comment_mark='#'):
    """Prefix authorship infomation to the given lines
    with given comment-mark.
    """
    prefix = ['%s Generated by the %s v%s' % (comment_mark,
              __software__, __version__)]
    prefix += ['%s    !author: %s' % (comment_mark, __author__)]
    prefix += ['%s    !trail: %s %s' % (comment_mark,
               os.path.basename(sys.argv[0]), ' '.join(sys.argv[1:]))]
    return prefix + lines


#-----------------------------------------------------------------------------

def read_xls(fn='dic.xls'):
    """Read Excel files and return value-list lines.
    """
    sheet = xlrd.open_workbook(fn).sheet_by_index(0)
    lines = (sheet.row_values(y) for y in xrange(sheet.nrows))
    lines = ([unicode(v).strip() for v in values] for values in lines)
    lines = (values for values in lines if values[0].lower() != 'x')
    lines = list(lines)
    marks, lines = lines[0][1:], lines[1:]
    lines = [[v for m, v in zip(marks, values[1:]) if m.lower() != 'x']
             for values in lines]
    return lines

#-----------------------------------------------------------------------------

def main():
    pass

if __name__ == '__main__':
    lines = read_xls()

