# -*- coding: utf-8 -*-
"""
The purpose of the tool are:
1) language translating
2) OSD indexing
"""
__software__ = "Multi-language converting tool"
__version__ = "1.00"
__author__ = "Jiang Yu-Kuan <york_jiang@mars-semi.com.tw>"
__date__ = "2012/11/27 (initial version) ~ 2012/11/29 (last revision)"

import os
import sys
import re
from itertools import izip

import xlrd


#-----------------------------------------------------------------------------

def save_utf8_file(fn, lines):
    """Save string lines into an UTF8 text files.
    """
    out_file = open(fn, "w")
    out_file.write("\n".join(lines).encode("utf-8"))
    out_file.close()


def save_utf16_file(fn, lines):
    """Save string lines into an UTF16 text files.
    """
    out_file = open(fn, "wb")
    out_file.write("\r\n".join(lines).encode("utf-16"))
    out_file.close()


def read_unicode(fn):
    """Read a unicode file that may encode with utf_16_le, utf_16_be, or utf_8.
    """
    from codecs import BOM_UTF16_LE, BOM_UTF16_BE, BOM_UTF8

    in_file = open(fn, "rb")
    bs = in_file.read()
    in_file.close()

    if  bs.startswith(BOM_UTF16_LE):
        us = bs.decode("utf_16_le").lstrip(BOM_UTF16_LE.decode("utf_16_le"))
    elif  bs.startswith(BOM_UTF16_BE):
        us = bs.decode("utf_16_be").lstrip(BOM_UTF16_BE.decode("utf_16_be"))
    else:
        us = bs.decode("utf_8").lstrip(BOM_UTF8.decode("utf_8"))

    return us


#-----------------------------------------------------------------------------

def read_xls(fn='dic.xls'):
    """Read Excel files and return heads, rows.
    """
    sheet = xlrd.open_workbook(fn).sheet_by_index(0)
    rows = (sheet.row_values(y) for y in xrange(sheet.nrows))
    rows = ([unicode(v).strip() for v in values] for values in rows)
    rows = (values[1:] for values in rows if values[0].lower() != 'x')
    cols = (values[1:] for values in izip(*rows) if values[0].lower() != 'x')
    rows = izip(*cols)
    return list(rows)


def read_char_lst(fn):
    """Return char:index items from a given char list file.
    """
    lines = read_unicode(fn).splitlines()
    lines = (x.rstrip() for x in lines)
    lines = (x for x in lines if len(x) > 0 and not x.startswith('#'))
    idx = 0
    dic = {}
    repeated = set()
    for line in lines:
        if line.startswith(':'):
            offset = eval(line[1:])
            if str(offset).isdigit():
                idx = offset
        else:
            repeated |= set(line) & set(dic)
            idxes = range(idx, idx + len(line))
            dic.update(zip(line, idxes))
            idx += len(line)
    return dic, sorted(list(repeated))


#-----------------------------------------------------------------------------

def seq_divide(sequence, modulus):
    """Divide a sequence into multiple sub-sequences.
    >>> seq_divide('abcdefghijklmnopqr', 4)
    ['abcd', 'efgh', 'ijkl', 'mnop', 'qr']
    """
    return [sequence[i:i + modulus] for i in xrange(0, len(sequence), modulus)]


def main_basename(path):
    """Return a main name of a basename of a given file path.
    """
    base = os.path.basename(path)
    base_main, base_ext = os.path.splitext(base)
    return base_main


def replace_chars(text, replaced_pairs='', deleted_chars=''):
    """Return a char replaced text.

    Arguments
    ---------
    text -- the text
    replaced_pairs -- the replaced chars

    Example
    -------
    >>> replaced = [('a','b'), ('c','d')]
    >>> removed = 'e'
    >>> replace_chars('abcde', replaced, removed)
    'bbdd'
    """
    for old, new in replaced_pairs:
        text = text.replace(old, new)
    for ch in deleted_chars:
        text = text.replace(ch, '')
    return text


def camel_case(string):
    return ''.join(w.capitalize() for w in string.split())


def replace_punctuations(text):
    punctuations = [
        ('?', 'Q'),   # Q:  question mark
        ('.', 'P'),   # P:  period; full stop
        ('!', 'E'),   # E:  exclamation mark
        ("'", 'SQ'),  # SQ: single quotation mark; single quote
        ('"', 'DQ'),  # DQ: double quotation mark; double quotes
        ('(', 'LP'),  # LP: left parenthese
        (')', 'RP'),  # RP: right parenthese
        (':', 'Cn'),  # Cn: colon
        (',', 'Ca'),  # Ca: comma
        (';', 'S'),   # S:  semicolon
    ]
    deleted = '+-*/^=%$#@|\\<>{}[]'
    return replace_chars(text, punctuations, deleted)


def remain_alnum(text):
    """Remain digit and English letter.
    """
    return ''.join(c for c in text if c.isalnum()
                                   and ord(' ') <= ord(c) <= ord('z'))


#-----------------------------------------------------------------------------

def prefix_authorship(lines, comment_mark='#'):
    """Prefix authorship infomation to the given lines
    with given comment-mark.
    """
    prefix = ['%s Generated by the %s v%s' % (comment_mark,
              __software__, __version__)]
    prefix += ['%s    !author: %s' % (comment_mark, __author__)]
    prefix += ['%s    !trail: %s %s' % (comment_mark,
               os.path.basename(sys.argv[0]), ' '.join(sys.argv[1:]))]
    return prefix + lines


def wrap_header_guard(lines, h_fn):
    """Wrap a C header guard for a given line list.
    """
    h_fn_sig = '_%s_H' % main_basename(h_fn).upper()
    begin = ['#ifndef %s' % h_fn_sig]
    begin += ['#define %s' % h_fn_sig, '', '']
    end = ['', '', '#endif // %s' % h_fn_sig, '']
    return begin + lines + end


def c_identifier(text):
    """Convert input text into an legal identifier in C.
    >>> c_identifier("Hello World")
    'HelloWorld'
    >>> c_identifier("Anti-Shake")
    'Antishake'
    """
    if ' ' in text:
        text = camel_case(text)
    text = re.sub(r'\+\d+', lambda x: x.group().replace('+', 'P'), text)
    text = re.sub(r'\-\d+', lambda x: x.group().replace('-', 'N'), text)
    text = replace_punctuations(text)
    return remain_alnum(text)


#-----------------------------------------------------------------------------

def get_lang_names(rows):
    """
    Get language names
    """
    heads = rows[0]
    return [h for h in heads if h.upper() != 'ID']


def gen_msg_ids(rows):
    """
    Generate message IDs
    """
    heads, records = rows[0], rows[1:]
    heads = [h.upper() for h in heads]
    cols = zip(*records)
    ids = cols[heads.index('ID')]
    en_msgs = cols[heads.index('ENGLISH')]
    ids = [id or en_msg for id, en_msg in zip(ids, en_msgs)]
    return [c_identifier(id) for id in ids]


#-----------------------------------------------------------------------------

def gen_lang_id_hfile(rows, h_fn):
    """Generate a C header file of language ID enumeration.
    """
    lines = ['/** Language Indexes */']
    lines += ['typedef enum {']
    lines += ['    L_%s,' % lang for lang in get_lang_names(rows)]
    lines += ['    L_End,']
    lines += ['    L_Total = L_End']
    lines += ['} Lang;']

    lines = wrap_header_guard(lines, h_fn)
    lines = prefix_authorship(lines, comment_mark='//')
    save_utf8_file(h_fn, lines)


def gen_msg_id_hfile(rows, h_fn):
    """Generate a C header file of message ID enumeration.
    """
    lines = ['/** IDs of Messages */']
    lines += ["typedef enum {"]
    lines += ['    MSG_%s,' % id for id in gen_msg_ids(rows)]
    lines += ['    MSG_End,']
    lines += ['    MSG_Total = MSG_End']
    lines += ['} MsgId;']

    lines = wrap_header_guard(lines, h_fn)
    lines = prefix_authorship(lines, comment_mark='//')
    save_utf8_file(h_fn, lines)


def verify_and_report(rows, char_lst_fn, report_fn):
    """Generate a report file to list used-but-not-listing chars and
    listig-but-not-used chars.
    """
    def get_mlang_records(rows):
        """Get records without ID column
        """
        heads, records = rows[0], rows[1:]
        heads = [h.upper() for h in heads]
        i = heads.index('ID')
        return [r[:i] + r[i+1:] for r in records]

    char_use = set([])
    for r in get_mlang_records(rows):
        char_use |= set(''.join(r))

    char_tbl, ch_rep = read_char_lst(char_lst_fn)
    char_lst = set(char_tbl)

    char_not_lst = sorted(char_use - char_lst)
    char_not_use = sorted(char_lst - char_use)

    lines = []
    if char_not_lst != []:
        lines += ['', '# Chars used but not listed:']
        lines += seq_divide(''.join(char_not_lst), 10)
    if char_not_use != []:
        lines += ['', '# Chars listed but not used:']
        lines += seq_divide(''.join(char_not_use), 10)

    lines = prefix_authorship(lines, comment_mark='#')
    save_utf16_file(report_fn, lines)


def gen_mlang_ifile(rows, char_lst_fn, c_fn):
    """Generate a C included file to list char indexs array for multilanguage
    messages.
    """
    pass


def main():
    pass


if __name__ == '__main__':
    rows = read_xls()
    gen_lang_id_hfile(rows, 'lang_id.h')
    gen_msg_id_hfile(rows, 'msg_id.h')
    verify_and_report(rows, 'char.lst', 'verify.report')
    gen_mlang_msg_cfile(rows, 'char.lst', 'mlang.c')

